### ISSUE TITLE
No daemon problem

### ISSUE THREAD

**Issue by Riseryn** [corus87/kalliope_tweaks#1]
Hi
I'm trying to use your tweak but i have the following error.
```
File "/home/pi/.local/lib/python3.7/site-packages/kalliope/signals/order/order.py", line 97, in start_trigger_process
    self.trigger_instance.daemon = True
AttributeError: 'NoneType' object has no attribute 'daemon'
```
I have followed the installation instruction and run
```
ansible-playbook install.yml -K
```
in the ownsnowboy folder.

**Comment by corus87** [comment]
Took me some time to reproduce your error but I think you forgot to change the trigger in your settings.

e.g:
```
default_trigger: "ownsnowboy"
triggers:
  - ownsnowboy:
      pmdl_file: "trigger/jarvis.umdl"
      sensitivity: 
        - 0.55
        - 0.55
```

**Comment by Riseryn** [comment]
Effectively i forgotten to do that.
Now i have this error
```
 File "resources/trigger/ownsnowboy/ownsnowboy.py", line 11, in <module>
    from snowboydecoder import HotwordDetector
  File "/home/pi/kalliope_starter_fr/resources/trigger/ownsnowboy/snowboydecoder.py", line 16, in <module>
    from kalliope.stt.Utils import SpeechRecorder
ImportError: cannot import name 'SpeechRecorder' from 'kalliope.stt.Utils' (/home/pi/.local/lib/python3.7/site-packages/kalliope/stt/Utils.py)
```

**Comment by corus87** [comment]
Did you placed the ```Utils.py``` and  ```OwnSpeech.py``` in ```kalliope/stt/``` ? 
Also did you run the setup again with ```sudo python3 setup.py install``` again?
 
It is possible that you need to remove the build folder in the main kalliope folder.

**Comment by Riseryn** [comment]
I placed Utils.py and OwnSpeech.py in kalliope_starter_fr/resources/stt
and run ansible-playbook install.yml -K

**Comment by corus87** [comment]
Ah there is your problem. 
You have to place it in the kalliope install folder. 
I guess you installed kalliope by pip? 
You should install kalliope manual, just use [Method 2 - Manual setup using sources](https://kalliope-project.github.io/kalliope/installation/ubuntu/). 
After cloning the project and ```cd kalliope```, replace the Utils.py  in kalliope/stt  and also put the OwnSpeech.py in  the kalliope/stt folder.

**Comment by Riseryn** [comment]
I tried method 2 and still the same problem.

**Comment by corus87** [comment]
But you still tried to start kalliope from kalliope_starter_fr ?

Did you found the original Utils.py?

**Comment by Riseryn** [comment]
It completely brokes my kalliope installation. Kalliope doesnt work anymore.
I have this error

 File "/home/pi/.local/lib/python3.7/site-packages/kalliope/core/TriggerLauncher.py", line 29, in get_trigger
    trigger.parameters["callback"] = callback
TypeError: 'NoneType' object does not support item assignment

**Comment by Riseryn** [comment]
False alert. i forgot to uncomment a line in my settings. I rolled back to snowboy.

**Comment by Riseryn** [comment]
I have an other problem with the gkeep neuron but i will open an issue in its page

**Comment by corus87** [comment]
> I tried method 2 and still the same problem.

If you have the same problem, then you did something wrong. You have to install Kalliope manual, replace Utils.py and place OwnSpeech.py in kalliope/stt.
Run the setup again with ```sudo python3 setup.py install``` and start kalliope again from your starter kit. 
I will close this one, feel free to open again.
